title: "{$sep}-=( {$sep}Ustawienia {$sep})=-"
rows: 6
sound: ITEM_BOOK_PAGE_TURN

options:
  back:
    posx: 1
    posy: 1
    material: PLAYER_HEAD
    name: '{$p}Powrót'
    lore: [ '{$s}Wróć do menu Nexusa.' ]
    skull: "{$gui-back}"
  light-blue-stained-glass-pane:
    slots: [ 1, 2, 6, 7, 8, 9, 17, 18, 21, 23, 26, 27, 29, 30, 32, 33, 35, 36, 39, 41, 44, 45, 53 ]
    material: LIGHT_BLUE_STAINED_GLASS_PANE
    name: ''
  upgrade:
    posx: 5
    posy: 4
    material: NETHER_STAR
    upgrade:
      condition: "level < max_level"
      name: "{$sp}Ulepsz{$colon} {$s}%roman@level% {$arrow} {$s}%roman@next_level%"
      material: NETHER_STAR
      lvl-I:
        condition: 'level == 1'
        lore: |
          {$dot} {$p}&lRóżne Ulepszenia{$colon}
            {$sdot} {$s}Odblokuj Szaleństwo

          {$dot} {$p}&lWzmocnienia{$colon}
            {$sdot} {$s}Wszystkie Ulepszenia{$colon} {$sp}{$lvlup} Poziom 30

          {$dot} {$p}&lUlepszenia Czempiona{$colon}
            {$sdot} {$s}Odblokuj Rzut
            {$sdot} {$s}Odblokuj Limit Obrażeń
            {$sdot} {$s}Zdrowie{$colon} {$sp}{$lvlup} Poziom 30

          {$dot} {$p}&lWieżyczki{$colon}
            {$sdot} {$s}Odblokuj Wieżyczkę Leczącą
            {$sdot} {$s}Odblokuj Wieżyczkę Ognistą

          {$dot} {$p}&lStruktury{$colon}
            {$sdot} {$s}Odblokuj Powercell
            {$sdot} {$s}Odblokuj Posterunek

          {$p}Maksymalny Poziom{$colon} {$s}%roman@max_level%
          {$p}Koszt{$colon} {$s}%fancy@upgrade_cost%
      lvl-II:
        condition: 'level == 2'
        lore: |
          {$dot} {$p}&lRóżne Ulepszenia{$colon}
            {$sdot} {$s}Odblokuj Strażników
            {$sdot} {$s}Odblokuj Chwałę
            {$sdot} {$s}Odblokuj Zachowanie Ekwipunku

          {$dot} {$p}&lWzmocnienia{$colon}
            {$sdot} {$s}Wszystkie Ulepszenia{$colon} {$sp}{$lvlup} Poziom 40

          {$dot} {$p}&lUlepszenia Czempiona{$colon}
            {$sdot} {$s}Odblokuj Przeciągnięcie
            {$sdot} {$s}Odblokuj Thora
            {$sdot} {$s}Zdrowie{$colon} {$sp}{$lvlup} Poziom 40

          {$dot} {$p}&lWieżyczki{$colon}
            {$sdot} {$s}Odblokuj Psioniczną Wieżyczkę
            {$sdot} {$s}Odblokuj Piekielną Wieżyczkę

          {$dot} {$p}&lStruktury{$colon}
            {$sdot} {$s}Odblokuj Ekstraktor

          {$p}Maksymalny Poziom{$colon} {$s}%roman@max_level%
          {$p}Koszt{$colon} {$s}%fancy@upgrade_cost%
      lvl-III:
        condition: 'level == 3'
        lore: |
          {$dot} {$p}&lRóżne Ulepszenia{$colon}
            {$sdot} {$s}Odblokuj Strażników Nexusa
            {$sdot} {$s}Zachowanie Ekwipunku{$colon}: {$sp}{$lvlup} Poziom 2

          {$dot} {$p}&lWzmocnienia{$colon}
            {$sdot} {$s}Wszystkie Ulepszenia{$colon} {$sp}{$lvlup} Poziom 50

          {$dot} {$p}&lUlepszenia Czempiona{$colon}
            {$sdot} {$s}Odblokuj Posilki

          {$dot} {$p}&lWieżyczki{$colon}
            {$sdot} {$s}Odblokuj Wieżyczkę Promieniującą Ciepłem
            {$sdot} {$s}Odblokuj Wieżyczkę Żołnierza

          {$dot} {$p}&lStruktury{$colon}
            {$sdot} {$s}Odblokuj Strukturę WarpPad
            {$sdot} {$s}Odblokuj Strukturę Regulatora

          {$p}Maksymalny Poziom{$colon} {$s}%roman@max_level%
          {$p}Koszt{$colon} {$s}%fancy@upgrade_cost%
      lvl-IV:
        condition: 'level == 4'
        lore: |
          {$dot} {$p}&lRóżne Ulepszenia{$colon}
            {$sdot} {$s}Odblokuj Latanie
            {$sdot} {$s}Zachowanie Ekwipunku{$colon}: {$sp}{$lvlup} Poziom 3

          {$dot} {$p}&lWzmocnienia{$colon}
            {$sdot} {$s}Wszystkie Ulepszenia{$colon} {$sp}{$lvlup} Poziom 70

          {$dot} {$p}&lUlepszenia Czempiona{$colon}
            {$sdot} {$s}Odblokuj Wybuch

          {$dot} {$p}&lWieżyczki{$colon}
            {$sdot} {$s}Odblokuj Inferno Wieżyczkę

          {$dot} {$p}&lStruktury{$colon}
            {$sdot} {$s}Odblokuj Oblężniczą Armatę

          {$p}Maksymalny Poziom{$colon} {$s}%roman@max_level%
          {$p}Koszt{$colon} {$s}%fancy@upgrade_cost%
      else:
        lore: [ "&cNieznane Ulepszenie Królestwa: %level%" ]
    maxxed:
      name: "{$sp}Poziom Królestwa{$colon} {$s}%roman@level% {$sep}(&5Maksymalny{$sep})"
      material: NETHER_STAR
  public-home:
    posx: 4
    posy: 1
    material: DARK_OAK_DOOR
    name: "{$s}Otwarty Dom{$colon} %bool@kingdoms_kingdom_home_is_public%"
    lore: |
      {$sep}Gdy twój dom jest otwarty, każdy
      może się do niego teleportować używając
      {$p}/k home %kingdoms_kingdom_name%

      {$p}Lewy przycisk myszy{$sep} aby przełączyć.
      {$p}Prawy przycisk myszy{$sep} aby ustawić koszt.
      Koszt dotyczy tylko osób spoza
      twojego królestwa.
      {$p}Aktualny Podatek Domu{$colon} {$s}%kingdoms_kingdom_taxes_home%

      {$note} Oba królestwa muszą mieć
      atrybut HOME, aby to działało.
  hidden:
    posx: 5
    posy: 1
    material: POTION
    color: 818595
    name: "{$s}Ukryte{$colon} %bool@kingdoms_kingdom_is_hidden%"
    lore: |
      {$sep}Ukryte królestwa nie są wyświetlane
      w {$p}/k map {$sep}ani na mapach online.
  tax:
    posx: 6
    posy: 1
    material: PAPER
    name: '{$s}Podatek'
    lore: |
      {$sep}Zmień podatki w swoim królestwie
      dla członków.

      {$s}Równanie Podatku{$colon}
      {$p}%tax_equation%
      {$s}Twój Podatek{$colon} {$p}$%fancy@kingdoms_tax%

      {$s}Podatek Królestwa{$colon} {$p}$%fancy@kingdoms_kingdom_tax%
  blue-stained-glass-pane:
    slots: [ 10, 11, 12, 13, 14, 15, 16, 19, 25, 28, 34, 37, 43, 46, 47, 48, 49, 50, 51, 52 ]
    material: BLUE_STAINED_GLASS_PANE
    name: ''
  relations:
    posx: 3
    posy: 3
    material: WRITABLE_BOOK
    name: '{$s}Relacje'
    lore: |
      {$sep}Zmień atrybuty relacji
      z innymi królestwami.

      {$sep}[&e!{$sep}] {$es}Aby niektóre atrybuty działały,
      oba królestwa muszą mieć je włączone
      dla tej relacji.

      Jeśli masz {$e}BUDOWA{$es} dla sojuszników,
      ale sojusznik nie ma tego atrybutu,
      nie będziesz mógł budować.
  banners:
    posx: 5
    posy: 3
    material: BLACK_BANNER
    name: '{$s}Flagi i Bannery'
    lore: |
      {$sep}Ustaw flagę i banner królestwa
      dla map online, ikon i dekoracji.
  pacifism:
    posx: 7
    posy: 3
    material: END_CRYSTAL
    name: '{$s}Pacyfista{$colon} %bool@kingdoms_kingdom_is_pacifist%'
    lore: |
      {$sep}W trybie pacyfisty twoje królestwo
      nie może najeżdżać ani być najeżdżane.

      Jeśli dokonasz najazdu, nie możesz wrócić
      do trybu pacyfisty przez tydzień.
      {? pacifism_left > 0 ? "
      {$p}Czas Odnowienia{$colon} {$s}%pacifism_cooldown%" }
  invites:
    posx: 3
    posy: 5
    material: BOOK
    name: '{$s}Wymaga Zaproszenia{$colon} %bool@kingdoms_kingdom_requires_invite%'
    lore: |
      {$sep}Gdy wyłączone, każdy może
      dołączyć do królestwa bez zaproszenia
      używając {$p}/k join %kingdoms_kingdom_name%
  color:
    posx: 5
    posy: 5
    material: LIME_DYE
    name: '{$s}Kolor{$colon} &c%r%{$sep}, {$p}%g%{$sep}, {$sp}%b% {$sep}(%hex@kingdoms_kingdom_color%%kingdoms_kingdom_color%{$sep})'
    lore: |
      {$sep}Ustaw kolor znacznika królestwa
      dla czatu i map online.
  shields:
    posx: 7
    posy: 5
    material: SHIELD
    name: '{$s}Tarcza{$colon} {$p}%time@kingdoms_shield_time_left%'
    lore: |
      {$sep}Kup tarczę, aby chronić
      królestwo przed najazdami.